export const FLAGS_CONFIG = [
  { emoji: '🇦🇫', name: 'Afghanistan', country: 'Afghanistan' },
  { emoji: '🇦🇱', name: 'Albania', country: 'Albania' },
  { emoji: '🇩🇿', name: 'Algeria', country: 'Algeria' },
  { emoji: '🇦🇩', name: 'Andorra', country: 'Andorra' },
  { emoji: '🇦🇴', name: 'Angola', country: 'Angola' },
  { emoji: '🇦🇬', name: 'Antigua and Barbuda', country: 'Antigua and Barbuda' },
  { emoji: '🇦🇷', name: 'Argentina', country: 'Argentina' },
  { emoji: '🇦🇲', name: 'Armenia', country: 'Armenia' },
  { emoji: '🇦🇺', name: 'Australia', country: 'Australia' },
  { emoji: '🇦🇹', name: 'Austria', country: 'Austria' },
  { emoji: '🇦🇿', name: 'Azerbaijan', country: 'Azerbaijan' },
  { emoji: '🇧🇸', name: 'Bahamas', country: 'Bahamas' },
  { emoji: '🇧🇭', name: 'Bahrain', country: 'Bahrain' },
  { emoji: '🇧🇩', name: 'Bangladesh', country: 'Bangladesh' },
  { emoji: '🇧🇧', name: 'Barbados', country: 'Barbados' },
  { emoji: '🇧🇾', name: 'Belarus', country: 'Belarus' },
  { emoji: '🇧🇪', name: 'Belgium', country: 'Belgium' },
  { emoji: '🇧🇿', name: 'Belize', country: 'Belize' },
  { emoji: '🇧🇯', name: 'Benin', country: 'Benin' },
  { emoji: '🇧🇹', name: 'Bhutan', country: 'Bhutan' },
  { emoji: '🇧🇴', name: 'Bolivia', country: 'Bolivia' },
  { emoji: '🇧🇦', name: 'Bosnia and Herzegovina', country: 'Bosnia and Herzegovina' },
  { emoji: '🇧🇼', name: 'Botswana', country: 'Botswana' },
  { emoji: '🇧🇷', name: 'Brazil', country: 'Brazil' },
  { emoji: '🇧🇳', name: 'Brunei', country: 'Brunei' },
  { emoji: '🇧🇬', name: 'Bulgaria', country: 'Bulgaria' },
  { emoji: '🇧🇫', name: 'Burkina Faso', country: 'Burkina Faso' },
  { emoji: '🇧🇮', name: 'Burundi', country: 'Burundi' },
  { emoji: '🇰🇭', name: 'Cambodia', country: 'Cambodia' },
  { emoji: '🇨🇲', name: 'Cameroon', country: 'Cameroon' },
  { emoji: '🇨🇦', name: 'Canada', country: 'Canada' },
  { emoji: '🇨🇻', name: 'Cape Verde', country: 'Cape Verde' },
  { emoji: '🇨🇫', name: 'Central African Republic', country: 'Central African Republic' },
  { emoji: '🇹🇩', name: 'Chad', country: 'Chad' },
  { emoji: '🇨🇱', name: 'Chile', country: 'Chile' },
  { emoji: '🇨🇳', name: 'China', country: 'China' },
  { emoji: '🇨🇴', name: 'Colombia', country: 'Colombia' },
  { emoji: '🇰🇲', name: 'Comoros', country: 'Comoros' },
  { emoji: '🇨🇬', name: 'Congo', country: 'Congo' },
  { emoji: '🇨🇷', name: 'Costa Rica', country: 'Costa Rica' },
  { emoji: '🇭🇷', name: 'Croatia', country: 'Croatia' },
  { emoji: '🇨🇺', name: 'Cuba', country: 'Cuba' },
  { emoji: '🇨🇾', name: 'Cyprus', country: 'Cyprus' },
  { emoji: '🇨🇿', name: 'Czech Republic', country: 'Czech Republic' },
  { emoji: '🇨🇮', name: 'Côte d\'Ivoire', country: 'Côte d\'Ivoire' },
  { emoji: '🇨🇩', name: 'Democratic Republic of the Congo', country: 'Democratic Republic of the Congo' },
  { emoji: '🇩🇰', name: 'Denmark', country: 'Denmark' },
  { emoji: '🇩🇯', name: 'Djibouti', country: 'Djibouti' },
  { emoji: '🇩🇲', name: 'Dominica', country: 'Dominica' },
  { emoji: '🇩🇴', name: 'Dominican Republic', country: 'Dominican Republic' },
  { emoji: '🇪🇨', name: 'Ecuador', country: 'Ecuador' },
  { emoji: '🇪🇬', name: 'Egypt', country: 'Egypt' },
  { emoji: '🇸🇻', name: 'El Salvador', country: 'El Salvador' },
  { emoji: '🇬🇶', name: 'Equatorial Guinea', country: 'Equatorial Guinea' },
  { emoji: '🇪🇷', name: 'Eritrea', country: 'Eritrea' },
  { emoji: '🇪🇪', name: 'Estonia', country: 'Estonia' },
  { emoji: '🇸🇿', name: 'Eswatini', country: 'Eswatini' },
  { emoji: '🇪🇹', name: 'Ethiopia', country: 'Ethiopia' },
  { emoji: '🇫🇯', name: 'Fiji', country: 'Fiji' },
  { emoji: '🇫🇮', name: 'Finland', country: 'Finland' },
  { emoji: '🇫🇷', name: 'France', country: 'France' },
  { emoji: '🇬🇦', name: 'Gabon', country: 'Gabon' },
  { emoji: '🇬🇲', name: 'Gambia', country: 'Gambia' },
  { emoji: '🇬🇪', name: 'Georgia', country: 'Georgia' },
  { emoji: '🇩🇪', name: 'Germany', country: 'Germany' },
  { emoji: '🇬🇭', name: 'Ghana', country: 'Ghana' },
  { emoji: '🇬🇷', name: 'Greece', country: 'Greece' },
  { emoji: '🇬🇩', name: 'Grenada', country: 'Grenada' },
  { emoji: '🇬🇹', name: 'Guatemala', country: 'Guatemala' },
  { emoji: '🇬🇳', name: 'Guinea', country: 'Guinea' },
  { emoji: '🇬🇼', name: 'Guinea-Bissau', country: 'Guinea-Bissau' },
  { emoji: '🇬🇾', name: 'Guyana', country: 'Guyana' },
  { emoji: '🇭🇹', name: 'Haiti', country: 'Haiti' },
  { emoji: '🇭🇳', name: 'Honduras', country: 'Honduras' },
  { emoji: '🇭🇺', name: 'Hungary', country: 'Hungary' },
  { emoji: '🇮🇸', name: 'Iceland', country: 'Iceland' },
  { emoji: '🇮🇳', name: 'India', country: 'India' },
  { emoji: '🇮🇩', name: 'Indonesia', country: 'Indonesia' },
  { emoji: '🇮🇷', name: 'Iran', country: 'Iran' },
  { emoji: '🇮🇶', name: 'Iraq', country: 'Iraq' },
  { emoji: '🇮🇪', name: 'Ireland', country: 'Ireland' },
  { emoji: '🇮🇱', name: 'Israel', country: 'Israel' },
  { emoji: '🇮🇹', name: 'Italy', country: 'Italy' },
  { emoji: '🇯🇲', name: 'Jamaica', country: 'Jamaica' },
  { emoji: '🇯🇵', name: 'Japan', country: 'Japan' },
  { emoji: '🇯🇴', name: 'Jordan', country: 'Jordan' },
  { emoji: '🇰🇿', name: 'Kazakhstan', country: 'Kazakhstan' },
  { emoji: '🇰🇪', name: 'Kenya', country: 'Kenya' },
  { emoji: '🇰🇮', name: 'Kiribati', country: 'Kiribati' },
  { emoji: '🇰🇼', name: 'Kuwait', country: 'Kuwait' },
  { emoji: '🇰🇬', name: 'Kyrgyzstan', country: 'Kyrgyzstan' },
  { emoji: '🇱🇦', name: 'Laos', country: 'Laos' },
  { emoji: '🇱🇻', name: 'Latvia', country: 'Latvia' },
  { emoji: '🇱🇧', name: 'Lebanon', country: 'Lebanon' },
  { emoji: '🇱🇸', name: 'Lesotho', country: 'Lesotho' },
  { emoji: '🇱🇷', name: 'Liberia', country: 'Liberia' },
  { emoji: '🇱🇾', name: 'Libya', country: 'Libya' },
  { emoji: '🇱🇮', name: 'Liechtenstein', country: 'Liechtenstein' },
  { emoji: '🇱🇹', name: 'Lithuania', country: 'Lithuania' },
  { emoji: '🇱🇺', name: 'Luxembourg', country: 'Luxembourg' },
  { emoji: '🇲🇬', name: 'Madagascar', country: 'Madagascar' },
  { emoji: '🇲🇼', name: 'Malawi', country: 'Malawi' },
  { emoji: '🇲🇾', name: 'Malaysia', country: 'Malaysia' },
  { emoji: '🇲🇻', name: 'Maldives', country: 'Maldives' },
  { emoji: '🇲🇱', name: 'Mali', country: 'Mali' },
  { emoji: '🇲🇹', name: 'Malta', country: 'Malta' },
  { emoji: '🇲🇭', name: 'Marshall Islands', country: 'Marshall Islands' },
  { emoji: '🇲🇷', name: 'Mauritania', country: 'Mauritania' },
  { emoji: '🇲🇺', name: 'Mauritius', country: 'Mauritius' },
  { emoji: '🇲🇽', name: 'Mexico', country: 'Mexico' },
  { emoji: '🇫🇲', name: 'Micronesia', country: 'Micronesia' },
  { emoji: '🇲🇩', name: 'Moldova', country: 'Moldova' },
  { emoji: '🇲🇨', name: 'Monaco', country: 'Monaco' },
  { emoji: '🇲🇳', name: 'Mongolia', country: 'Mongolia' },
  { emoji: '🇲🇪', name: 'Montenegro', country: 'Montenegro' },
  { emoji: '🇲🇦', name: 'Morocco', country: 'Morocco' },
  { emoji: '🇲🇿', name: 'Mozambique', country: 'Mozambique' },
  { emoji: '🇲🇲', name: 'Myanmar', country: 'Myanmar' },
  { emoji: '🇳🇦', name: 'Namibia', country: 'Namibia' },
  { emoji: '🇳🇷', name: 'Nauru', country: 'Nauru' },
  { emoji: '🇳🇵', name: 'Nepal', country: 'Nepal' },
  { emoji: '🇳🇱', name: 'Netherlands', country: 'Netherlands' },
  { emoji: '🇳🇿', name: 'New Zealand', country: 'New Zealand' },
  { emoji: '🇳🇮', name: 'Nicaragua', country: 'Nicaragua' },
  { emoji: '🇳🇪', name: 'Niger', country: 'Niger' },
  { emoji: '🇳🇬', name: 'Nigeria', country: 'Nigeria' },
  { emoji: '🇰🇵', name: 'North Korea', country: 'North Korea' },
  { emoji: '🇲🇰', name: 'North Macedonia', country: 'North Macedonia' },
  { emoji: '🇳🇴', name: 'Norway', country: 'Norway' },
  { emoji: '🇴🇲', name: 'Oman', country: 'Oman' },
  { emoji: '🇵🇰', name: 'Pakistan', country: 'Pakistan' },
  { emoji: '🇵🇼', name: 'Palau', country: 'Palau' },
  { emoji: '🇵🇦', name: 'Panama', country: 'Panama' },
  { emoji: '🇵🇬', name: 'Papua New Guinea', country: 'Papua New Guinea' },
  { emoji: '🇵🇾', name: 'Paraguay', country: 'Paraguay' },
  { emoji: '🇵🇪', name: 'Peru', country: 'Peru' },
  { emoji: '🇵🇭', name: 'Philippines', country: 'Philippines' },
  { emoji: '🇵🇱', name: 'Poland', country: 'Poland' },
  { emoji: '🇵🇹', name: 'Portugal', country: 'Portugal' },
  { emoji: '🇶🇦', name: 'Qatar', country: 'Qatar' },
  { emoji: '🇷🇴', name: 'Romania', country: 'Romania' },
  { emoji: '🇷🇺', name: 'Russia', country: 'Russia' },
  { emoji: '🇷🇼', name: 'Rwanda', country: 'Rwanda' },
  { emoji: '🇰🇳', name: 'Saint Kitts and Nevis', country: 'Saint Kitts and Nevis' },
  { emoji: '🇱🇨', name: 'Saint Lucia', country: 'Saint Lucia' },
  { emoji: '🇻🇨', name: 'Saint Vincent and the Grenadines', country: 'Saint Vincent and the Grenadines' },
  { emoji: '🇼🇸', name: 'Samoa', country: 'Samoa' },
  { emoji: '🇸🇲', name: 'San Marino', country: 'San Marino' },
  { emoji: '🇸🇹', name: 'Sao Tome and Principe', country: 'Sao Tome and Principe' },
  { emoji: '🇸🇦', name: 'Saudi Arabia', country: 'Saudi Arabia' },
  { emoji: '🇸🇳', name: 'Senegal', country: 'Senegal' },
  { emoji: '🇷🇸', name: 'Serbia', country: 'Serbia' },
  { emoji: '🇸🇨', name: 'Seychelles', country: 'Seychelles' },
  { emoji: '🇸🇱', name: 'Sierra Leone', country: 'Sierra Leone' },
  { emoji: '🇸🇬', name: 'Singapore', country: 'Singapore' },
  { emoji: '🇸🇰', name: 'Slovakia', country: 'Slovakia' },
  { emoji: '🇸🇮', name: 'Slovenia', country: 'Slovenia' },
  { emoji: '🇸🇧', name: 'Solomon Islands', country: 'Solomon Islands' },
  { emoji: '🇸🇴', name: 'Somalia', country: 'Somalia' },
  { emoji: '🇿🇦', name: 'South Africa', country: 'South Africa' },
  { emoji: '🇰🇷', name: 'South Korea', country: 'South Korea' },
  { emoji: '🇸🇸', name: 'South Sudan', country: 'South Sudan' },
  { emoji: '🇪🇸', name: 'Spain', country: 'Spain' },
  { emoji: '🇱🇰', name: 'Sri Lanka', country: 'Sri Lanka' },
  { emoji: '🇸🇩', name: 'Sudan', country: 'Sudan' },
  { emoji: '🇸🇷', name: 'Suriname', country: 'Suriname' },
  { emoji: '🇸🇪', name: 'Sweden', country: 'Sweden' },
  { emoji: '🇨🇭', name: 'Switzerland', country: 'Switzerland' },
  { emoji: '🇸🇾', name: 'Syria', country: 'Syria' },
  { emoji: '🇹🇼', name: 'Taiwan', country: 'Taiwan' },
  { emoji: '🇹🇯', name: 'Tajikistan', country: 'Tajikistan' },
  { emoji: '🇹🇿', name: 'Tanzania', country: 'Tanzania' },
  { emoji: '🇹🇭', name: 'Thailand', country: 'Thailand' },
  { emoji: '🇹🇱', name: 'Timor-Leste', country: 'Timor-Leste' },
  { emoji: '🇹🇬', name: 'Togo', country: 'Togo' },
  { emoji: '🇹🇴', name: 'Tonga', country: 'Tonga' },
  { emoji: '🇹🇹', name: 'Trinidad and Tobago', country: 'Trinidad and Tobago' },
  { emoji: '🇹🇳', name: 'Tunisia', country: 'Tunisia' },
  { emoji: '🇹🇷', name: 'Turkey', country: 'Turkey' },
  { emoji: '🇹🇲', name: 'Turkmenistan', country: 'Turkmenistan' },
  { emoji: '🇹🇻', name: 'Tuvalu', country: 'Tuvalu' },
  { emoji: '🇺🇬', name: 'Uganda', country: 'Uganda' },
  { emoji: '🇺🇦', name: 'Ukraine', country: 'Ukraine' },
  { emoji: '🇦🇪', name: 'United Arab Emirates', country: 'United Arab Emirates' },
  { emoji: '🇬🇧', name: 'United Kingdom', country: 'United Kingdom' },
  { emoji: '🇺🇸', name: 'United States', country: 'United States' },
  { emoji: '🇺🇾', name: 'Uruguay', country: 'Uruguay' },
  { emoji: '🇺🇿', name: 'Uzbekistan', country: 'Uzbekistan' },
  { emoji: '🇻🇺', name: 'Vanuatu', country: 'Vanuatu' },
  { emoji: '🇻🇦', name: 'Vatican City', country: 'Vatican City' },
  { emoji: '🇻🇪', name: 'Venezuela', country: 'Venezuela' },
  { emoji: '🇻🇳', name: 'Vietnam', country: 'Vietnam' },
  { emoji: '🇾🇪', name: 'Yemen', country: 'Yemen' },
  { emoji: '🇿🇲', name: 'Zambia', country: 'Zambia' },
  { emoji: '🇿🇼', name: 'Zimbabwe', country: 'Zimbabwe' }
]; 